sudo: required

dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.cache/composer
    - $HOME/.phpbrew
    - $HOME/.npm

branches:
  only:
    - master

# Before install, failures in this section will result in build status 'errored'
before_install:
  - |
    docker run --rm -v "$PWD:/app" -v "$HOME/.cache/composer:/tmp/cache" composer install

script:
  - |
    if [[ "$SCRIPT" == "lint" ]]; then
      composer lint || exit 1
    fi
  - |
    if [[ "$SCRIPT" == "unit" ]]; then
      composer coverage || exit 1
    fi

jobs:
  allow_failures:
    - php: nightly
  include:
    - stage: test
      name: Lint
      php: 7.3
      env: PHPCS_PHP_VERSION='5.4' SCRIPT=lint
    - name: PHP Tests (PHP 5.6)
      php: 5.6
      env: SCRIPT=unit
    - name: PHP Tests (PHP 7.4)
      php: 7.4
      env: SCRIPT=unit

services:
  - docker
